import type {
  Appointment,
  Doctor,
  FinancialSummary,
  Invoice,
  LabReport,
  Notification,
  Patient,
  PatientActivity,
  Prescription,
  RevenueData,
  StaffMember,
  TherapySession,
  User,
} from "@/types";

export const MOCK_USERS: Record<string, User> = {
  super_admin: {
    id: "u1",
    name: "Dr. Sarah Mitchell",
    role: "super_admin",
    department: "Admin",
    email: "sarah.mitchell@physiosync.com",
    phone: "+1-555-0101",
    avatar: undefined,
  },
  doctor: {
    id: "u2",
    name: "Dr. James Reeves",
    role: "doctor",
    department: "PMR",
    email: "james.reeves@physiosync.com",
    phone: "+1-555-0102",
    specialization: "Physical Medicine & Rehabilitation",
  },
  receptionist: {
    id: "u3",
    name: "Emily Torres",
    role: "receptionist",
    department: "General",
    email: "emily.torres@physiosync.com",
    phone: "+1-555-0103",
  },
  sales: {
    id: "u4",
    name: "Marcus Reid",
    role: "sales",
    department: "Admin",
    email: "sales@clinic.com",
    phone: "+1-555-0104",
  },
  patient: {
    id: "u5",
    name: "Jordan Mitchell",
    role: "patient",
    department: "General",
    email: "patient@clinic.com",
    phone: "+1-617-555-8001",
  },
};

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "d1",
    name: "Dr. James Reeves",
    specialization: "Physical Medicine & Rehabilitation",
    department: "PMR",
    email: "james.reeves@physiosync.com",
    phone: "+1-555-0102",
    patientsCount: 48,
    rating: 4.9,
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    experience: 12,
  },
  {
    id: "d2",
    name: "Dr. Priya Sharma",
    specialization: "Physiotherapy",
    department: "PMR",
    email: "priya.sharma@physiosync.com",
    phone: "+1-555-0104",
    patientsCount: 35,
    rating: 4.8,
    availability: ["Mon", "Wed", "Fri"],
    experience: 8,
  },
  {
    id: "d3",
    name: "Dr. Michael Chen",
    specialization: "Orthopedic Rehabilitation",
    department: "PMR",
    email: "michael.chen@physiosync.com",
    phone: "+1-555-0105",
    patientsCount: 52,
    rating: 4.7,
    availability: ["Tue", "Thu", "Sat"],
    experience: 15,
  },
  {
    id: "d4",
    name: "Dr. Aisha Khan",
    specialization: "General Medicine",
    department: "General",
    email: "aisha.khan@physiosync.com",
    phone: "+1-555-0106",
    patientsCount: 41,
    rating: 4.6,
    availability: ["Mon", "Tue", "Wed", "Thu"],
    experience: 10,
  },
  {
    id: "d5",
    name: "Dr. Robert Walsh",
    specialization: "Sports Medicine",
    department: "General",
    email: "robert.walsh@physiosync.com",
    phone: "+1-555-0107",
    patientsCount: 29,
    rating: 4.8,
    availability: ["Mon", "Wed", "Thu", "Fri"],
    experience: 9,
  },
];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p1",
    patientId: "PSY-2024-001",
    name: "Marcus Johnson",
    age: 42,
    gender: "Male",
    dob: "1982-03-15",
    phone: "+1-555-1001",
    email: "marcus.j@email.com",
    address: "142 Oak Street, Boston MA 02101",
    bloodGroup: "A+",
    department: "PMR",
    assignedDoctor: "Dr. James Reeves",
    status: "active",
    registeredDate: "2024-01-10",
    insurance: "BlueCross BlueShield",
    emergencyContact: "+1-555-1002",
    medicalHistory: [
      "Lumbar disc herniation",
      "Chronic lower back pain",
      "Previous knee surgery (2019)",
    ],
    allergies: ["Penicillin", "Sulfa drugs"],
  },
  {
    id: "p2",
    patientId: "PSY-2024-002",
    name: "Linda Park",
    age: 35,
    gender: "Female",
    dob: "1989-07-22",
    phone: "+1-555-1003",
    email: "linda.park@email.com",
    address: "88 Maple Ave, Cambridge MA 02139",
    bloodGroup: "O-",
    department: "PMR",
    assignedDoctor: "Dr. Priya Sharma",
    status: "active",
    registeredDate: "2024-01-15",
    insurance: "Aetna",
    emergencyContact: "+1-555-1004",
    medicalHistory: ["Rotator cuff tear", "Frozen shoulder"],
    allergies: ["Aspirin"],
  },
  {
    id: "p3",
    patientId: "PSY-2024-003",
    name: "Thomas Wright",
    age: 58,
    gender: "Male",
    dob: "1966-11-08",
    phone: "+1-555-1005",
    email: "thomas.w@email.com",
    address: "215 Pine Road, Brookline MA 02445",
    bloodGroup: "B+",
    department: "PMR",
    assignedDoctor: "Dr. Michael Chen",
    status: "active",
    registeredDate: "2024-02-01",
    insurance: "UnitedHealth",
    emergencyContact: "+1-555-1006",
    medicalHistory: [
      "Hip replacement (2022)",
      "Osteoarthritis",
      "Type 2 Diabetes",
    ],
    allergies: [],
  },
  {
    id: "p4",
    patientId: "PSY-2024-004",
    name: "Sofia Alvarez",
    age: 28,
    gender: "Female",
    dob: "1996-04-30",
    phone: "+1-555-1007",
    email: "sofia.a@email.com",
    address: "67 Elm Street, Somerville MA 02143",
    bloodGroup: "AB+",
    department: "General",
    assignedDoctor: "Dr. Aisha Khan",
    status: "active",
    registeredDate: "2024-02-10",
    insurance: "Harvard Pilgrim",
    emergencyContact: "+1-555-1008",
    medicalHistory: ["Migraine disorder", "Anxiety"],
    allergies: ["NSAIDs"],
  },
  {
    id: "p5",
    patientId: "PSY-2024-005",
    name: "David Kim",
    age: 45,
    gender: "Male",
    dob: "1979-09-12",
    phone: "+1-555-1009",
    email: "david.k@email.com",
    address: "320 Birch Lane, Newton MA 02458",
    bloodGroup: "O+",
    department: "PMR",
    assignedDoctor: "Dr. James Reeves",
    status: "active",
    registeredDate: "2024-02-15",
    insurance: "Cigna",
    emergencyContact: "+1-555-1010",
    medicalHistory: ["Cervical spondylosis", "Tennis elbow"],
    allergies: ["Latex"],
  },
  {
    id: "p6",
    patientId: "PSY-2024-006",
    name: "Rachel Green",
    age: 31,
    gender: "Female",
    dob: "1993-06-18",
    phone: "+1-555-1011",
    email: "rachel.g@email.com",
    address: "445 Cedar Blvd, Waltham MA 02451",
    bloodGroup: "A-",
    department: "PMR",
    assignedDoctor: "Dr. Priya Sharma",
    status: "active",
    registeredDate: "2024-03-01",
    insurance: "Tufts",
    emergencyContact: "+1-555-1012",
    medicalHistory: ["ACL reconstruction (2023)", "Patellar tendinitis"],
    allergies: [],
  },
  {
    id: "p7",
    patientId: "PSY-2024-007",
    name: "William Harris",
    age: 67,
    gender: "Male",
    dob: "1957-01-25",
    phone: "+1-555-1013",
    email: "w.harris@email.com",
    address: "78 Walnut St, Quincy MA 02169",
    bloodGroup: "B-",
    department: "General",
    assignedDoctor: "Dr. Robert Walsh",
    status: "active",
    registeredDate: "2024-03-05",
    insurance: "Medicare",
    emergencyContact: "+1-555-1014",
    medicalHistory: [
      "Hypertension",
      "Coronary artery disease",
      "Knee osteoarthritis",
    ],
    allergies: ["Codeine"],
  },
  {
    id: "p8",
    patientId: "PSY-2024-008",
    name: "Natalie Brown",
    age: 39,
    gender: "Female",
    dob: "1985-12-03",
    phone: "+1-555-1015",
    email: "natalie.b@email.com",
    address: "155 Spruce Ave, Medford MA 02155",
    bloodGroup: "AB-",
    department: "PMR",
    assignedDoctor: "Dr. Michael Chen",
    status: "active",
    registeredDate: "2024-03-10",
    insurance: "BlueCross BlueShield",
    emergencyContact: "+1-555-1016",
    medicalHistory: ["Plantar fasciitis", "Achilles tendinopathy"],
    allergies: ["Shellfish"],
  },
  {
    id: "p9",
    patientId: "PSY-2024-009",
    name: "Carlos Mendez",
    age: 53,
    gender: "Male",
    dob: "1971-05-20",
    phone: "+1-555-1017",
    email: "carlos.m@email.com",
    address: "290 Chestnut St, Malden MA 02148",
    bloodGroup: "A+",
    department: "General",
    assignedDoctor: "Dr. Aisha Khan",
    status: "inactive",
    registeredDate: "2024-01-20",
    insurance: "Fallon Health",
    emergencyContact: "+1-555-1018",
    medicalHistory: ["Type 2 Diabetes", "Peripheral neuropathy"],
    allergies: ["Ibuprofen"],
  },
  {
    id: "p10",
    patientId: "PSY-2024-010",
    name: "Jennifer White",
    age: 47,
    gender: "Female",
    dob: "1977-08-14",
    phone: "+1-555-1019",
    email: "jennifer.w@email.com",
    address: "512 Hawthorn Dr, Woburn MA 01801",
    bloodGroup: "O+",
    department: "PMR",
    assignedDoctor: "Dr. James Reeves",
    status: "active",
    registeredDate: "2024-04-01",
    insurance: "Aetna",
    emergencyContact: "+1-555-1020",
    medicalHistory: ["Fibromyalgia", "Chronic fatigue syndrome"],
    allergies: [],
  },
  {
    id: "p11",
    patientId: "PSY-2024-011",
    name: "Andrew Lee",
    age: 26,
    gender: "Male",
    dob: "1998-02-11",
    phone: "+1-555-1021",
    email: "andrew.lee@email.com",
    address: "33 Ash Street, Everett MA 02149",
    bloodGroup: "B+",
    department: "General",
    assignedDoctor: "Dr. Robert Walsh",
    status: "active",
    registeredDate: "2024-04-05",
    insurance: "UnitedHealth",
    emergencyContact: "+1-555-1022",
    medicalHistory: ["Sports injury - shoulder", "Mild scoliosis"],
    allergies: [],
  },
  {
    id: "p12",
    patientId: "PSY-2024-012",
    name: "Patricia Moore",
    age: 62,
    gender: "Female",
    dob: "1962-10-28",
    phone: "+1-555-1023",
    email: "patricia.m@email.com",
    address: "670 Magnolia Ln, Lexington MA 02420",
    bloodGroup: "A+",
    department: "PMR",
    assignedDoctor: "Dr. Priya Sharma",
    status: "active",
    registeredDate: "2024-04-10",
    insurance: "Medicare",
    emergencyContact: "+1-555-1024",
    medicalHistory: ["Post-stroke rehabilitation", "Hypertension", "Diabetes"],
    allergies: ["Penicillin"],
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    patientName: "Marcus Johnson",
    doctorId: "d1",
    doctorName: "Dr. James Reeves",
    department: "PMR",
    date: "2026-05-19",
    time: "09:00",
    duration: 60,
    status: "confirmed",
    type: "Physiotherapy Session",
    notes: "Continue lumbar stabilization exercises",
    tokenNumber: 1,
  },
  {
    id: "a2",
    patientId: "p2",
    patientName: "Linda Park",
    doctorId: "d2",
    doctorName: "Dr. Priya Sharma",
    department: "PMR",
    date: "2026-05-19",
    time: "09:30",
    duration: 45,
    status: "in_progress",
    type: "Follow-up Consultation",
    tokenNumber: 2,
  },
  {
    id: "a3",
    patientId: "p3",
    patientName: "Thomas Wright",
    doctorId: "d3",
    doctorName: "Dr. Michael Chen",
    department: "PMR",
    date: "2026-05-19",
    time: "10:00",
    duration: 60,
    status: "scheduled",
    type: "Orthopedic Assessment",
    tokenNumber: 3,
  },
  {
    id: "a4",
    patientId: "p4",
    patientName: "Sofia Alvarez",
    doctorId: "d4",
    doctorName: "Dr. Aisha Khan",
    department: "General",
    date: "2026-05-19",
    time: "10:30",
    duration: 30,
    status: "scheduled",
    type: "General Checkup",
    tokenNumber: 4,
  },
  {
    id: "a5",
    patientId: "p5",
    patientName: "David Kim",
    doctorId: "d1",
    doctorName: "Dr. James Reeves",
    department: "PMR",
    date: "2026-05-19",
    time: "11:00",
    duration: 60,
    status: "scheduled",
    type: "Cervical Traction Therapy",
    tokenNumber: 5,
  },
  {
    id: "a6",
    patientId: "p6",
    patientName: "Rachel Green",
    doctorId: "d2",
    doctorName: "Dr. Priya Sharma",
    department: "PMR",
    date: "2026-05-19",
    time: "11:30",
    duration: 45,
    status: "completed",
    type: "Post-Op Rehabilitation",
    tokenNumber: 6,
  },
  {
    id: "a7",
    patientId: "p7",
    patientName: "William Harris",
    doctorId: "d5",
    doctorName: "Dr. Robert Walsh",
    department: "General",
    date: "2026-05-19",
    time: "14:00",
    duration: 30,
    status: "scheduled",
    type: "Cardiac Follow-up",
    tokenNumber: 7,
  },
  {
    id: "a8",
    patientId: "p8",
    patientName: "Natalie Brown",
    doctorId: "d3",
    doctorName: "Dr. Michael Chen",
    department: "PMR",
    date: "2026-05-19",
    time: "14:30",
    duration: 45,
    status: "scheduled",
    type: "Foot & Ankle Therapy",
    tokenNumber: 8,
  },
  {
    id: "a9",
    patientId: "p9",
    patientName: "Carlos Mendez",
    doctorId: "d4",
    doctorName: "Dr. Aisha Khan",
    department: "General",
    date: "2026-05-20",
    time: "09:00",
    duration: 30,
    status: "scheduled",
    type: "Diabetes Management",
    tokenNumber: 1,
  },
  {
    id: "a10",
    patientId: "p10",
    patientName: "Jennifer White",
    doctorId: "d1",
    doctorName: "Dr. James Reeves",
    department: "PMR",
    date: "2026-05-20",
    time: "09:30",
    duration: 60,
    status: "scheduled",
    type: "Fibromyalgia Therapy",
    tokenNumber: 2,
  },
  {
    id: "a11",
    patientId: "p1",
    patientName: "Marcus Johnson",
    doctorId: "d1",
    doctorName: "Dr. James Reeves",
    department: "PMR",
    date: "2026-05-15",
    time: "09:00",
    duration: 60,
    status: "completed",
    type: "Physiotherapy Session",
    tokenNumber: 1,
  },
  {
    id: "a12",
    patientId: "p2",
    patientName: "Linda Park",
    doctorId: "d2",
    doctorName: "Dr. Priya Sharma",
    department: "PMR",
    date: "2026-05-15",
    time: "10:00",
    duration: 45,
    status: "completed",
    type: "Shoulder Mobilization",
    tokenNumber: 2,
  },
  {
    id: "a13",
    patientId: "p11",
    patientName: "Andrew Lee",
    doctorId: "d5",
    doctorName: "Dr. Robert Walsh",
    department: "General",
    date: "2026-05-18",
    time: "15:00",
    duration: 30,
    status: "no_show",
    type: "Sports Assessment",
  },
  {
    id: "a14",
    patientId: "p12",
    patientName: "Patricia Moore",
    doctorId: "d2",
    doctorName: "Dr. Priya Sharma",
    department: "PMR",
    date: "2026-05-21",
    time: "10:00",
    duration: 60,
    status: "scheduled",
    type: "Stroke Rehabilitation",
  },
];

export const MOCK_LAB_REPORTS: LabReport[] = [
  {
    id: "lr1",
    patientId: "p1",
    patientName: "Marcus Johnson",
    testName: "MRI Lumbar Spine",
    orderedBy: "Dr. James Reeves",
    orderedDate: "2026-05-10",
    resultDate: "2026-05-12",
    status: "completed",
    category: "Imaging",
    results:
      "L4-L5 disc herniation with mild nerve root compression. No evidence of cauda equina syndrome.",
    isCritical: false,
  },
  {
    id: "lr2",
    patientId: "p3",
    patientName: "Thomas Wright",
    testName: "HbA1c Blood Panel",
    orderedBy: "Dr. Michael Chen",
    orderedDate: "2026-05-08",
    resultDate: "2026-05-09",
    status: "completed",
    category: "Hematology",
    results:
      "HbA1c: 7.8% (above target). FBG: 142 mg/dL. Lipid panel within normal limits.",
    isCritical: true,
  },
  {
    id: "lr3",
    patientId: "p7",
    patientName: "William Harris",
    testName: "Cardiac Stress Test",
    orderedBy: "Dr. Robert Walsh",
    orderedDate: "2026-05-14",
    status: "processing",
    category: "Cardiology",
    isCritical: false,
  },
  {
    id: "lr4",
    patientId: "p6",
    patientName: "Rachel Green",
    testName: "X-Ray Right Knee",
    orderedBy: "Dr. Priya Sharma",
    orderedDate: "2026-05-15",
    resultDate: "2026-05-15",
    status: "completed",
    category: "Imaging",
    results:
      "Post-ACL reconstruction. Hardware in good position. No signs of infection.",
    isCritical: false,
  },
  {
    id: "lr5",
    patientId: "p9",
    patientName: "Carlos Mendez",
    testName: "Nerve Conduction Study",
    orderedBy: "Dr. Aisha Khan",
    orderedDate: "2026-05-16",
    status: "pending",
    category: "Neurology",
    isCritical: false,
  },
  {
    id: "lr6",
    patientId: "p12",
    patientName: "Patricia Moore",
    testName: "Brain MRI with Contrast",
    orderedBy: "Dr. Priya Sharma",
    orderedDate: "2026-05-17",
    resultDate: "2026-05-18",
    status: "completed",
    category: "Imaging",
    results:
      "Stable post-stroke changes in left MCA territory. No new ischemic lesions.",
    isCritical: false,
  },
];

export const MOCK_PRESCRIPTIONS: Prescription[] = [
  {
    id: "rx1",
    patientId: "p1",
    patientName: "Marcus Johnson",
    doctorId: "d1",
    doctorName: "Dr. James Reeves",
    date: "2026-05-12",
    diagnosis: "Lumbar Disc Herniation with Radiculopathy",
    medicines: [
      {
        name: "Diclofenac Sodium",
        dosage: "75mg",
        frequency: "Twice daily",
        duration: "2 weeks",
        instructions: "Take with food",
      },
      {
        name: "Methocarbamol",
        dosage: "750mg",
        frequency: "Three times daily",
        duration: "1 week",
        instructions: "May cause drowsiness",
      },
      {
        name: "Pantoprazole",
        dosage: "40mg",
        frequency: "Once daily",
        duration: "2 weeks",
        instructions: "Take before meals",
      },
    ],
    notes: "Follow up in 2 weeks. Continue physiotherapy 3x/week.",
    status: "active",
  },
  {
    id: "rx2",
    patientId: "p4",
    patientName: "Sofia Alvarez",
    doctorId: "d4",
    doctorName: "Dr. Aisha Khan",
    date: "2026-05-10",
    diagnosis: "Migraine with Aura",
    medicines: [
      {
        name: "Sumatriptan",
        dosage: "50mg",
        frequency: "As needed (max 2/day)",
        duration: "30 days",
        instructions: "Take at onset of migraine",
      },
      {
        name: "Topiramate",
        dosage: "25mg",
        frequency: "Once daily at bedtime",
        duration: "90 days",
        instructions: "Prophylactic therapy",
      },
    ],
    status: "active",
  },
  {
    id: "rx3",
    patientId: "p3",
    patientName: "Thomas Wright",
    doctorId: "d3",
    doctorName: "Dr. Michael Chen",
    date: "2026-05-09",
    diagnosis: "Type 2 Diabetes - Medication Adjustment",
    medicines: [
      {
        name: "Metformin",
        dosage: "1000mg",
        frequency: "Twice daily",
        duration: "90 days",
        instructions: "Take with meals",
      },
      {
        name: "Jardiance (Empagliflozin)",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "90 days",
        instructions: "Monitor kidney function",
      },
    ],
    status: "active",
  },
  {
    id: "rx4",
    patientId: "p7",
    patientName: "William Harris",
    doctorId: "d5",
    doctorName: "Dr. Robert Walsh",
    date: "2026-05-05",
    diagnosis: "Hypertension Management",
    medicines: [
      {
        name: "Amlodipine",
        dosage: "5mg",
        frequency: "Once daily",
        duration: "90 days",
      },
      {
        name: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "90 days",
        instructions: "Monitor blood pressure daily",
      },
    ],
    status: "active",
  },
];

export const MOCK_THERAPY_SESSIONS: TherapySession[] = [
  {
    id: "ts1",
    patientId: "p1",
    patientName: "Marcus Johnson",
    therapistId: "d1",
    therapistName: "Dr. James Reeves",
    date: "2026-05-19",
    time: "09:00",
    sessionNumber: 8,
    totalSessions: 20,
    type: "Lumbar Stabilization",
    progress: 40,
    notes:
      "Patient showing improvement in core strength. Pain reduced from 7/10 to 4/10.",
    exercises: [
      "Pelvic tilts",
      "Dead bug exercise",
      "Bird dog",
      "Bridge exercise",
    ],
  },
  {
    id: "ts2",
    patientId: "p6",
    patientName: "Rachel Green",
    therapistId: "d2",
    therapistName: "Dr. Priya Sharma",
    date: "2026-05-19",
    time: "11:30",
    sessionNumber: 15,
    totalSessions: 24,
    type: "ACL Post-Op Rehab",
    progress: 62,
    notes:
      "Good quad strength recovery. Cleared for single-leg stance exercises.",
    exercises: [
      "Quad sets",
      "SLR",
      "Mini squats",
      "Leg press (40%)",
      "Balance board",
    ],
  },
  {
    id: "ts3",
    patientId: "p2",
    patientName: "Linda Park",
    therapistId: "d2",
    therapistName: "Dr. Priya Sharma",
    date: "2026-05-18",
    time: "10:00",
    sessionNumber: 6,
    totalSessions: 16,
    type: "Shoulder Mobilization",
    progress: 37,
    notes:
      "External rotation improved by 15 degrees. Continuing joint mobilization.",
    exercises: [
      "Codman pendulum",
      "Wall walks",
      "External rotation with band",
      "Scapular retraction",
    ],
  },
  {
    id: "ts4",
    patientId: "p12",
    patientName: "Patricia Moore",
    therapistId: "d2",
    therapistName: "Dr. Priya Sharma",
    date: "2026-05-20",
    time: "10:00",
    sessionNumber: 12,
    totalSessions: 36,
    type: "Stroke Rehabilitation",
    progress: 33,
    notes:
      "Upper limb coordination improving. Continue mirror therapy and functional tasks.",
    exercises: [
      "Mirror therapy",
      "Pegboard tasks",
      "Hand strengthening",
      "Gait training",
    ],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "lab_report",
    title: "Critical Lab Result",
    message:
      "Thomas Wright - HbA1c critically elevated at 7.8%. Immediate review required.",
    priority: "urgent",
    isRead: false,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    patientId: "p3",
    patientName: "Thomas Wright",
    actionUrl: "/doctor/patients/p3",
  },
  {
    id: "n2",
    type: "appointment",
    title: "New Appointment Booked",
    message:
      "Linda Park scheduled for Follow-up Consultation today at 9:30 AM.",
    priority: "medium",
    isRead: false,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    patientId: "p2",
    patientName: "Linda Park",
  },
  {
    id: "n3",
    type: "reminder",
    title: "Follow-up Reminder",
    message:
      "Marcus Johnson is due for his 2-week follow-up review of lumbar herniation treatment.",
    priority: "high",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    patientId: "p1",
    patientName: "Marcus Johnson",
  },
  {
    id: "n4",
    type: "prescription",
    title: "Prescription Refill Request",
    message: "Jennifer White has requested a refill for Duloxetine 60mg.",
    priority: "medium",
    isRead: false,
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    patientId: "p10",
    patientName: "Jennifer White",
  },
  {
    id: "n5",
    type: "billing",
    title: "Overdue Invoice",
    message:
      "Carlos Mendez has an overdue invoice of $450. Payment was due 3 days ago.",
    priority: "medium",
    isRead: true,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    patientId: "p9",
    patientName: "Carlos Mendez",
  },
  {
    id: "n6",
    type: "appointment",
    title: "No-Show Alert",
    message:
      "Andrew Lee missed his Sports Assessment appointment at 3:00 PM yesterday.",
    priority: "low",
    isRead: true,
    createdAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    patientId: "p11",
    patientName: "Andrew Lee",
  },
  {
    id: "n7",
    type: "system",
    title: "System Maintenance",
    message:
      "Scheduled maintenance window tonight 11 PM - 1 AM. System may be briefly unavailable.",
    priority: "low",
    isRead: true,
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv1",
    patientId: "p1",
    patientName: "Marcus Johnson",
    date: "2026-05-15",
    dueDate: "2026-05-30",
    items: [
      {
        description: "Physiotherapy Session (60 min)",
        quantity: 4,
        unitPrice: 120,
        total: 480,
      },
      {
        description: "MRI Scan - Lumbar",
        quantity: 1,
        unitPrice: 650,
        total: 650,
      },
    ],
    total: 1130,
    paid: 1130,
    status: "paid",
  },
  {
    id: "inv2",
    patientId: "p3",
    patientName: "Thomas Wright",
    date: "2026-05-10",
    dueDate: "2026-05-25",
    items: [
      {
        description: "Orthopedic Consultation",
        quantity: 2,
        unitPrice: 200,
        total: 400,
      },
      {
        description: "HbA1c Blood Panel",
        quantity: 1,
        unitPrice: 85,
        total: 85,
      },
    ],
    total: 485,
    paid: 250,
    status: "partial",
  },
  {
    id: "inv3",
    patientId: "p9",
    patientName: "Carlos Mendez",
    date: "2026-05-05",
    dueDate: "2026-05-16",
    items: [
      {
        description: "General Consultation",
        quantity: 1,
        unitPrice: 150,
        total: 150,
      },
      {
        description: "Diabetes Management Program",
        quantity: 3,
        unitPrice: 100,
        total: 300,
      },
    ],
    total: 450,
    paid: 0,
    status: "overdue",
  },
  {
    id: "inv4",
    patientId: "p6",
    patientName: "Rachel Green",
    date: "2026-05-18",
    dueDate: "2026-06-02",
    items: [
      {
        description: "ACL Rehabilitation Session",
        quantity: 5,
        unitPrice: 130,
        total: 650,
      },
      { description: "X-Ray Knee", quantity: 1, unitPrice: 180, total: 180 },
    ],
    total: 830,
    paid: 0,
    status: "pending",
  },
  {
    id: "inv5",
    patientId: "p12",
    patientName: "Patricia Moore",
    date: "2026-05-17",
    dueDate: "2026-06-01",
    items: [
      {
        description: "Stroke Rehabilitation (60 min)",
        quantity: 8,
        unitPrice: 140,
        total: 1120,
      },
      {
        description: "Brain MRI with Contrast",
        quantity: 1,
        unitPrice: 850,
        total: 850,
      },
    ],
    total: 1970,
    paid: 1000,
    status: "partial",
  },
];

export const MOCK_STAFF: StaffMember[] = [
  {
    id: "s1",
    name: "Emily Torres",
    role: "Receptionist",
    department: "General",
    email: "emily.torres@physiosync.com",
    phone: "+1-555-0103",
    joinDate: "2023-06-01",
    status: "active",
  },
  {
    id: "s2",
    name: "Ryan Patel",
    role: "Lab Technician",
    department: "General",
    email: "ryan.patel@physiosync.com",
    phone: "+1-555-0108",
    joinDate: "2023-09-15",
    status: "active",
  },
  {
    id: "s3",
    name: "Maria Santos",
    role: "Pharmacist",
    department: "General",
    email: "maria.santos@physiosync.com",
    phone: "+1-555-0109",
    joinDate: "2022-03-10",
    status: "active",
  },
  {
    id: "s4",
    name: "Jake Morrison",
    role: "Physiotherapy Assistant",
    department: "PMR",
    email: "jake.m@physiosync.com",
    phone: "+1-555-0110",
    joinDate: "2024-01-05",
    status: "active",
  },
  {
    id: "s5",
    name: "Chloe Bennett",
    role: "Billing Specialist",
    department: "Admin",
    email: "chloe.b@physiosync.com",
    phone: "+1-555-0111",
    joinDate: "2023-11-20",
    status: "active",
  },
];

export const MOCK_FINANCIAL: FinancialSummary = {
  totalRevenue: 284750,
  monthlyRevenue: 41200,
  pendingPayments: 12850,
  expenses: 18600,
  netProfit: 22600,
  revenueGrowth: 12.4,
  patientGrowth: 8.7,
  appointmentGrowth: 15.2,
};

export const MOCK_REVENUE_DATA: RevenueData[] = [
  { month: "Nov", revenue: 28400, expenses: 14200, patients: 89 },
  { month: "Dec", revenue: 31200, expenses: 15800, patients: 97 },
  { month: "Jan", revenue: 33500, expenses: 16200, patients: 104 },
  { month: "Feb", revenue: 36800, expenses: 17100, patients: 112 },
  { month: "Mar", revenue: 38200, expenses: 17800, patients: 118 },
  { month: "Apr", revenue: 39100, expenses: 18200, patients: 123 },
  { month: "May", revenue: 41200, expenses: 18600, patients: 131 },
];

export const MOCK_PATIENT_ACTIVITIES: PatientActivity[] = [
  {
    id: "pa1",
    type: "appointment",
    title: "Physiotherapy Session",
    description: "Session #8 - Lumbar Stabilization. Good progress noted.",
    date: "2026-05-19",
    time: "09:00",
    by: "Dr. James Reeves",
    status: "completed",
  },
  {
    id: "pa2",
    type: "lab",
    title: "MRI Results Uploaded",
    description: "MRI Lumbar Spine results: L4-L5 disc herniation confirmed.",
    date: "2026-05-12",
    time: "14:30",
    by: "Ryan Patel",
    status: "critical",
  },
  {
    id: "pa3",
    type: "prescription",
    title: "Prescription Updated",
    description: "Diclofenac + Methocarbamol prescribed for 2 weeks.",
    date: "2026-05-12",
    time: "11:00",
    by: "Dr. James Reeves",
  },
  {
    id: "pa4",
    type: "payment",
    title: "Invoice Paid",
    description: "Invoice #INV-001 for $1,130 paid in full via insurance.",
    date: "2026-05-15",
    time: "16:00",
    status: "paid",
  },
  {
    id: "pa5",
    type: "appointment",
    title: "Physiotherapy Session",
    description: "Session #7 completed. Introduced bridge exercise.",
    date: "2026-05-15",
    time: "09:00",
    by: "Dr. James Reeves",
    status: "completed",
  },
  {
    id: "pa6",
    type: "note",
    title: "Doctor Note Added",
    description:
      "Follow-up review: Patient reports reduced pain. Continuing current protocol.",
    date: "2026-05-10",
    time: "12:30",
    by: "Dr. James Reeves",
  },
  {
    id: "pa7",
    type: "notification",
    title: "Appointment Reminder Sent",
    description: "WhatsApp reminder sent for upcoming session.",
    date: "2026-05-18",
    time: "09:00",
  },
  {
    id: "pa8",
    type: "therapy",
    title: "Home Exercise Program",
    description:
      "New home exercise program provided: 4 exercises, twice daily.",
    date: "2026-05-08",
    time: "10:00",
    by: "Dr. James Reeves",
  },
];

// ─── NEW TYPES ─────────────────────────────────────────────────────────────────

export type LeadSource =
  | "sales_person"
  | "social_media_facebook"
  | "social_media_instagram"
  | "manual_entry"
  | "walk_in"
  | "referral"
  | "other";

export type LeadStatus = "new" | "contacted" | "converted" | "rejected";

export interface Lead {
  id: string;
  name: string;
  phone: string;
  email: string;
  status: LeadStatus;
  source: LeadSource;
  assignedTo: string;
  department: "PMR" | "General";
  createdAt: string;
  notes: string;
}

export type RoleName =
  | "super_admin"
  | "doctor"
  | "receptionist"
  | "sales"
  | "lab_staff"
  | "pharmacist"
  | "patient";

export type PageKey =
  | "dashboard"
  | "patients"
  | "appointments"
  | "leads"
  | "staff"
  | "analytics"
  | "billing"
  | "pharmacy"
  | "laboratory"
  | "reports"
  | "settings"
  | "permissions"
  | "audit_logs"
  | "reception_mgmt"
  | "sales_mgmt"
  | "lab_mgmt";

export type FunctionKey = "view" | "create" | "edit" | "delete";

export type PagePermissions = Record<FunctionKey, boolean>;
export type RolePermissions = Record<PageKey, PagePermissions>;
export type PermissionsMap = Record<RoleName, RolePermissions>;

export interface DepartmentStats {
  totalStaff: number;
  activeToday: number;
  pendingTasks: number;
  completedToday: number;
  weeklyTrend: number[];
}

export interface ReceptionQueueEntry {
  tokenNumber: number;
  patientName: string;
  appointmentTime: string;
  status: "waiting" | "in_progress" | "completed";
  doctor: string;
}

export interface SalesPerformance {
  staffName: string;
  leadsGenerated: number;
  conversions: number;
  conversionRate: number;
  visitsMade: number;
  callsMade: number;
  revenue: number;
}

export interface LabReportEntry {
  reportId: string;
  patientName: string;
  testType: string;
  requestedBy: string;
  uploadedAt: string;
  status: "pending" | "uploaded" | "verified";
  fileUrl: string;
}

export interface PharmacyInventoryItem {
  medicineId: string;
  name: string;
  category: string;
  stock: number;
  minStock: number;
  expiryDate: string;
  supplier: string;
  price: number;
  status: "in_stock" | "low_stock" | "out_of_stock";
}

// ─── MOCK LEADS ────────────────────────────────────────────────────────────────

export const MOCK_LEADS: Lead[] = [
  {
    id: "l1",
    name: "Arjun Nair",
    phone: "+1-617-555-3001",
    email: "arjun.nair@gmail.com",
    status: "new",
    source: "social_media_facebook",
    assignedTo: "Marcus Reid",
    department: "PMR",
    createdAt: "2026-05-18T09:15:00Z",
    notes:
      "Interested in physiotherapy for lower back pain. Saw our Facebook ad.",
  },
  {
    id: "l2",
    name: "Fatima Al-Hassan",
    phone: "+1-617-555-3002",
    email: "fatima.hassan@email.com",
    status: "contacted",
    source: "social_media_instagram",
    assignedTo: "Diana Blake",
    department: "PMR",
    createdAt: "2026-05-17T11:30:00Z",
    notes:
      "Saw gym promo reel on Instagram. Interested in sports rehab program.",
  },
  {
    id: "l3",
    name: "Liam O'Brien",
    phone: "+1-617-555-3003",
    email: "liam.obrien@email.com",
    status: "converted",
    source: "referral",
    assignedTo: "Marcus Reid",
    department: "General",
    createdAt: "2026-05-15T08:00:00Z",
    notes:
      "Referred by existing patient Marcus Johnson. Booked for general checkup.",
  },
  {
    id: "l4",
    name: "Preethi Subramaniam",
    phone: "+1-617-555-3004",
    email: "preethi.s@email.com",
    status: "new",
    source: "sales_person",
    assignedTo: "Marcus Reid",
    department: "PMR",
    createdAt: "2026-05-20T10:00:00Z",
    notes: "Lead from hospital visit outreach at City Hospital.",
  },
  {
    id: "l5",
    name: "Ethan Caldwell",
    phone: "+1-617-555-3005",
    email: "ethan.c@email.com",
    status: "contacted",
    source: "walk_in",
    assignedTo: "Emily Torres",
    department: "General",
    createdAt: "2026-05-19T14:20:00Z",
    notes:
      "Walked in asking about sports injury consultation. Provided brochure.",
  },
  {
    id: "l6",
    name: "Simone Laurent",
    phone: "+1-617-555-3006",
    email: "simone.l@email.com",
    status: "rejected",
    source: "social_media_facebook",
    assignedTo: "Diana Blake",
    department: "PMR",
    createdAt: "2026-05-14T09:00:00Z",
    notes: "Out of service area. Cannot accommodate travel distance.",
  },
  {
    id: "l7",
    name: "Ravi Krishnan",
    phone: "+1-617-555-3007",
    email: "ravi.k@email.com",
    status: "converted",
    source: "sales_person",
    assignedTo: "Marcus Reid",
    department: "PMR",
    createdAt: "2026-05-10T08:30:00Z",
    notes:
      "Gym partnership lead — FitLife gym referral. Enrolled in rehab program.",
  },
  {
    id: "l8",
    name: "Olivia Hartmann",
    phone: "+1-617-555-3008",
    email: "olivia.h@email.com",
    status: "new",
    source: "social_media_instagram",
    assignedTo: "Diana Blake",
    department: "General",
    createdAt: "2026-05-20T07:45:00Z",
    notes:
      "Saw before/after story on Instagram. Interested in post-natal physiotherapy.",
  },
  {
    id: "l9",
    name: "James Okafor",
    phone: "+1-617-555-3009",
    email: "james.okafor@email.com",
    status: "contacted",
    source: "manual_entry",
    assignedTo: "Marcus Reid",
    department: "PMR",
    createdAt: "2026-05-16T13:00:00Z",
    notes:
      "Entered manually after phone call inquiry. Needs cervical pain consultation.",
  },
  {
    id: "l10",
    name: "Neha Gupta",
    phone: "+1-617-555-3010",
    email: "neha.gupta@email.com",
    status: "converted",
    source: "referral",
    assignedTo: "Emily Torres",
    department: "General",
    createdAt: "2026-05-12T10:00:00Z",
    notes:
      "Referred by Dr. Walsh from another clinic. Registered as new patient.",
  },
  {
    id: "l11",
    name: "Carlos Vega",
    phone: "+1-617-555-3011",
    email: "carlos.vega@email.com",
    status: "new",
    source: "other",
    assignedTo: "Diana Blake",
    department: "PMR",
    createdAt: "2026-05-19T16:00:00Z",
    notes: "Lead from community health fair at Copley Square.",
  },
  {
    id: "l12",
    name: "Anika Mehta",
    phone: "+1-617-555-3012",
    email: "anika.mehta@email.com",
    status: "contacted",
    source: "social_media_facebook",
    assignedTo: "Marcus Reid",
    department: "General",
    createdAt: "2026-05-17T15:30:00Z",
    notes:
      "Responded to paid Facebook campaign. Interested in general wellness checkup.",
  },
  {
    id: "l13",
    name: "Tom Bradley",
    phone: "+1-617-555-3013",
    email: "tom.bradley@email.com",
    status: "rejected",
    source: "walk_in",
    assignedTo: "Emily Torres",
    department: "General",
    createdAt: "2026-05-13T11:00:00Z",
    notes: "Walk-in inquiry but patient requires services not offered here.",
  },
  {
    id: "l14",
    name: "Zara Hussain",
    phone: "+1-617-555-3014",
    email: "zara.hussain@email.com",
    status: "converted",
    source: "social_media_instagram",
    assignedTo: "Diana Blake",
    department: "PMR",
    createdAt: "2026-05-09T09:00:00Z",
    notes: "Instagram DM lead. Enrolled in physiotherapy for frozen shoulder.",
  },
  {
    id: "l15",
    name: "Samuel Osei",
    phone: "+1-617-555-3015",
    email: "samuel.osei@email.com",
    status: "new",
    source: "sales_person",
    assignedTo: "Marcus Reid",
    department: "PMR",
    createdAt: "2026-05-20T09:00:00Z",
    notes: "Corporate wellness program outreach at TechCorp offices.",
  },
  {
    id: "l16",
    name: "Isabella Rossi",
    phone: "+1-617-555-3016",
    email: "isabella.r@email.com",
    status: "contacted",
    source: "referral",
    assignedTo: "Emily Torres",
    department: "General",
    createdAt: "2026-05-15T12:00:00Z",
    notes:
      "Referred by Patricia Moore. Interested in general medicine consultation.",
  },
  {
    id: "l17",
    name: "Daniel Cho",
    phone: "+1-617-555-3017",
    email: "daniel.cho@email.com",
    status: "converted",
    source: "manual_entry",
    assignedTo: "Marcus Reid",
    department: "PMR",
    createdAt: "2026-05-08T08:00:00Z",
    notes: "Manually added after email inquiry. Now registered for knee rehab.",
  },
  {
    id: "l18",
    name: "Layla Al-Farsi",
    phone: "+1-617-555-3018",
    email: "layla.alfarsi@email.com",
    status: "contacted",
    source: "social_media_facebook",
    assignedTo: "Diana Blake",
    department: "General",
    createdAt: "2026-05-16T10:30:00Z",
    notes:
      "Facebook lead from promotional post about general health screening.",
  },
  {
    id: "l19",
    name: "Victor Petrov",
    phone: "+1-617-555-3019",
    email: "victor.p@email.com",
    status: "new",
    source: "other",
    assignedTo: "Marcus Reid",
    department: "PMR",
    createdAt: "2026-05-20T08:00:00Z",
    notes: "Referred via physio directory listing on HealthGrades website.",
  },
  {
    id: "l20",
    name: "Mei Ling",
    phone: "+1-617-555-3020",
    email: "mei.ling@email.com",
    status: "converted",
    source: "walk_in",
    assignedTo: "Emily Torres",
    department: "PMR",
    createdAt: "2026-05-11T14:00:00Z",
    notes: "Walk-in registration. Immediately booked for PMR consultation.",
  },
  {
    id: "l21",
    name: "Noah Williams",
    phone: "+1-617-555-3021",
    email: "noah.w@email.com",
    status: "rejected",
    source: "sales_person",
    assignedTo: "Diana Blake",
    department: "General",
    createdAt: "2026-05-18T15:00:00Z",
    notes: "Lead from gym outreach but patient decided not to proceed.",
  },
  {
    id: "l22",
    name: "Aisha Traoré",
    phone: "+1-617-555-3022",
    email: "aisha.traore@email.com",
    status: "new",
    source: "social_media_instagram",
    assignedTo: "Marcus Reid",
    department: "General",
    createdAt: "2026-05-20T11:00:00Z",
    notes:
      "Instagram story inquiry about nutrition and general health consultation.",
  },
];

// ─── MOCK PERMISSIONS ──────────────────────────────────────────────────────────

const allAccess: PagePermissions = {
  view: true,
  create: true,
  edit: true,
  delete: true,
};
const viewOnly: PagePermissions = {
  view: true,
  create: false,
  edit: false,
  delete: false,
};
const noAccess: PagePermissions = {
  view: false,
  create: false,
  edit: false,
  delete: false,
};
const viewCreate: PagePermissions = {
  view: true,
  create: true,
  edit: false,
  delete: false,
};
const viewCreateEdit: PagePermissions = {
  view: true,
  create: true,
  edit: true,
  delete: false,
};
const viewEdit: PagePermissions = {
  view: true,
  create: false,
  edit: true,
  delete: false,
};

export const MOCK_PERMISSIONS: PermissionsMap = {
  super_admin: {
    dashboard: allAccess,
    patients: allAccess,
    appointments: allAccess,
    leads: allAccess,
    staff: allAccess,
    analytics: allAccess,
    billing: allAccess,
    pharmacy: allAccess,
    laboratory: allAccess,
    reports: allAccess,
    settings: allAccess,
    permissions: allAccess,
    audit_logs: allAccess,
    reception_mgmt: allAccess,
    sales_mgmt: allAccess,
    lab_mgmt: allAccess,
  },
  doctor: {
    dashboard: viewOnly,
    patients: viewEdit,
    appointments: viewCreateEdit,
    leads: noAccess,
    staff: viewOnly,
    analytics: viewOnly,
    billing: viewOnly,
    pharmacy: viewOnly,
    laboratory: viewCreate,
    reports: viewOnly,
    settings: noAccess,
    permissions: noAccess,
    audit_logs: noAccess,
    reception_mgmt: noAccess,
    sales_mgmt: noAccess,
    lab_mgmt: noAccess,
  },
  receptionist: {
    dashboard: viewOnly,
    patients: viewCreateEdit,
    appointments: viewCreateEdit,
    leads: viewOnly,
    staff: viewOnly,
    analytics: noAccess,
    billing: viewCreate,
    pharmacy: noAccess,
    laboratory: noAccess,
    reports: viewOnly,
    settings: noAccess,
    permissions: noAccess,
    audit_logs: noAccess,
    reception_mgmt: viewEdit,
    sales_mgmt: noAccess,
    lab_mgmt: noAccess,
  },
  sales: {
    dashboard: viewOnly,
    patients: viewOnly,
    appointments: viewOnly,
    leads: viewCreateEdit,
    staff: noAccess,
    analytics: viewOnly,
    billing: noAccess,
    pharmacy: noAccess,
    laboratory: noAccess,
    reports: viewOnly,
    settings: noAccess,
    permissions: noAccess,
    audit_logs: noAccess,
    reception_mgmt: noAccess,
    sales_mgmt: viewEdit,
    lab_mgmt: noAccess,
  },
  lab_staff: {
    dashboard: viewOnly,
    patients: viewOnly,
    appointments: viewOnly,
    leads: noAccess,
    staff: noAccess,
    analytics: noAccess,
    billing: noAccess,
    pharmacy: noAccess,
    laboratory: viewCreateEdit,
    reports: viewCreate,
    settings: noAccess,
    permissions: noAccess,
    audit_logs: noAccess,
    reception_mgmt: noAccess,
    sales_mgmt: noAccess,
    lab_mgmt: viewEdit,
  },
  pharmacist: {
    dashboard: viewOnly,
    patients: viewOnly,
    appointments: viewOnly,
    leads: noAccess,
    staff: noAccess,
    analytics: noAccess,
    billing: viewCreate,
    pharmacy: viewCreateEdit,
    laboratory: noAccess,
    reports: viewOnly,
    settings: noAccess,
    permissions: noAccess,
    audit_logs: noAccess,
    reception_mgmt: noAccess,
    sales_mgmt: noAccess,
    lab_mgmt: noAccess,
  },
  patient: {
    dashboard: viewOnly,
    patients: viewOnly,
    appointments: viewCreate,
    leads: noAccess,
    staff: noAccess,
    analytics: noAccess,
    billing: viewOnly,
    pharmacy: noAccess,
    laboratory: viewOnly,
    reports: viewOnly,
    settings: viewEdit,
    permissions: noAccess,
    audit_logs: noAccess,
    reception_mgmt: noAccess,
    sales_mgmt: noAccess,
    lab_mgmt: noAccess,
  },
};

// ─── MOCK DEPARTMENT STATS ─────────────────────────────────────────────────────

export const MOCK_DEPARTMENT_STATS: Record<string, DepartmentStats> = {
  reception: {
    totalStaff: 6,
    activeToday: 5,
    pendingTasks: 12,
    completedToday: 38,
    weeklyTrend: [32, 41, 35, 48, 38, 44, 38],
  },
  sales: {
    totalStaff: 4,
    activeToday: 4,
    pendingTasks: 18,
    completedToday: 22,
    weeklyTrend: [15, 18, 22, 19, 25, 21, 22],
  },
  laboratory: {
    totalStaff: 5,
    activeToday: 4,
    pendingTasks: 7,
    completedToday: 19,
    weeklyTrend: [14, 17, 20, 16, 18, 22, 19],
  },
  pharmacy: {
    totalStaff: 3,
    activeToday: 3,
    pendingTasks: 4,
    completedToday: 31,
    weeklyTrend: [28, 30, 25, 33, 29, 32, 31],
  },
};

// ─── MOCK RECEPTION QUEUE ──────────────────────────────────────────────────────

export const MOCK_RECEPTION_QUEUE: ReceptionQueueEntry[] = [
  {
    tokenNumber: 1,
    patientName: "Marcus Johnson",
    appointmentTime: "09:00",
    status: "completed",
    doctor: "Dr. James Reeves",
  },
  {
    tokenNumber: 2,
    patientName: "Linda Park",
    appointmentTime: "09:30",
    status: "completed",
    doctor: "Dr. Priya Sharma",
  },
  {
    tokenNumber: 3,
    patientName: "Thomas Wright",
    appointmentTime: "10:00",
    status: "in_progress",
    doctor: "Dr. Michael Chen",
  },
  {
    tokenNumber: 4,
    patientName: "Sofia Alvarez",
    appointmentTime: "10:30",
    status: "waiting",
    doctor: "Dr. Aisha Khan",
  },
  {
    tokenNumber: 5,
    patientName: "David Kim",
    appointmentTime: "11:00",
    status: "waiting",
    doctor: "Dr. James Reeves",
  },
  {
    tokenNumber: 6,
    patientName: "Rachel Green",
    appointmentTime: "11:30",
    status: "waiting",
    doctor: "Dr. Priya Sharma",
  },
  {
    tokenNumber: 7,
    patientName: "William Harris",
    appointmentTime: "14:00",
    status: "waiting",
    doctor: "Dr. Robert Walsh",
  },
  {
    tokenNumber: 8,
    patientName: "Natalie Brown",
    appointmentTime: "14:30",
    status: "waiting",
    doctor: "Dr. Michael Chen",
  },
  {
    tokenNumber: 9,
    patientName: "Jennifer White",
    appointmentTime: "15:00",
    status: "waiting",
    doctor: "Dr. James Reeves",
  },
  {
    tokenNumber: 10,
    patientName: "Andrew Lee",
    appointmentTime: "15:30",
    status: "waiting",
    doctor: "Dr. Robert Walsh",
  },
];

// ─── MOCK SALES PERFORMANCE ────────────────────────────────────────────────────

export const MOCK_SALES_PERFORMANCE: SalesPerformance[] = [
  {
    staffName: "Marcus Reid",
    leadsGenerated: 32,
    conversions: 19,
    conversionRate: 59.4,
    visitsMade: 28,
    callsMade: 74,
    revenue: 38400,
  },
  {
    staffName: "Diana Blake",
    leadsGenerated: 27,
    conversions: 14,
    conversionRate: 51.9,
    visitsMade: 21,
    callsMade: 63,
    revenue: 28700,
  },
  {
    staffName: "Kevin Okafor",
    leadsGenerated: 22,
    conversions: 11,
    conversionRate: 50.0,
    visitsMade: 19,
    callsMade: 58,
    revenue: 22500,
  },
  {
    staffName: "Priya Malhotra",
    leadsGenerated: 18,
    conversions: 8,
    conversionRate: 44.4,
    visitsMade: 15,
    callsMade: 47,
    revenue: 16800,
  },
  {
    staffName: "Sam Torres",
    leadsGenerated: 15,
    conversions: 9,
    conversionRate: 60.0,
    visitsMade: 12,
    callsMade: 40,
    revenue: 18200,
  },
  {
    staffName: "Rachel Nguyen",
    leadsGenerated: 20,
    conversions: 10,
    conversionRate: 50.0,
    visitsMade: 17,
    callsMade: 52,
    revenue: 20100,
  },
  {
    staffName: "Ali Hassan",
    leadsGenerated: 12,
    conversions: 5,
    conversionRate: 41.7,
    visitsMade: 10,
    callsMade: 33,
    revenue: 10200,
  },
  {
    staffName: "Claire Fontaine",
    leadsGenerated: 25,
    conversions: 16,
    conversionRate: 64.0,
    visitsMade: 23,
    callsMade: 68,
    revenue: 32500,
  },
];

// ─── MOCK LAB REPORT ENTRIES (upload-centric) ─────────────────────────────────

export const MOCK_LAB_REPORT_ENTRIES: LabReportEntry[] = [
  {
    reportId: "RPT-001",
    patientName: "Marcus Johnson",
    testType: "MRI Lumbar Spine",
    requestedBy: "Dr. James Reeves",
    uploadedAt: "2026-05-12T14:30:00Z",
    status: "verified",
    fileUrl: "/files/reports/rpt-001.pdf",
  },
  {
    reportId: "RPT-002",
    patientName: "Thomas Wright",
    testType: "HbA1c Blood Panel",
    requestedBy: "Dr. Michael Chen",
    uploadedAt: "2026-05-09T10:00:00Z",
    status: "verified",
    fileUrl: "/files/reports/rpt-002.pdf",
  },
  {
    reportId: "RPT-003",
    patientName: "William Harris",
    testType: "Cardiac Stress Test",
    requestedBy: "Dr. Robert Walsh",
    uploadedAt: "",
    status: "pending",
    fileUrl: "",
  },
  {
    reportId: "RPT-004",
    patientName: "Rachel Green",
    testType: "X-Ray Right Knee",
    requestedBy: "Dr. Priya Sharma",
    uploadedAt: "2026-05-15T09:15:00Z",
    status: "verified",
    fileUrl: "/files/reports/rpt-004.pdf",
  },
  {
    reportId: "RPT-005",
    patientName: "Carlos Mendez",
    testType: "Nerve Conduction Study",
    requestedBy: "Dr. Aisha Khan",
    uploadedAt: "",
    status: "pending",
    fileUrl: "",
  },
  {
    reportId: "RPT-006",
    patientName: "Patricia Moore",
    testType: "Brain MRI with Contrast",
    requestedBy: "Dr. Priya Sharma",
    uploadedAt: "2026-05-18T11:00:00Z",
    status: "verified",
    fileUrl: "/files/reports/rpt-006.pdf",
  },
  {
    reportId: "RPT-007",
    patientName: "Sofia Alvarez",
    testType: "CBC with Differential",
    requestedBy: "Dr. Aisha Khan",
    uploadedAt: "2026-05-19T08:45:00Z",
    status: "uploaded",
    fileUrl: "/files/reports/rpt-007.pdf",
  },
  {
    reportId: "RPT-008",
    patientName: "David Kim",
    testType: "Cervical Spine X-Ray",
    requestedBy: "Dr. James Reeves",
    uploadedAt: "2026-05-17T15:30:00Z",
    status: "uploaded",
    fileUrl: "/files/reports/rpt-008.pdf",
  },
  {
    reportId: "RPT-009",
    patientName: "Natalie Brown",
    testType: "Ultrasound Right Foot",
    requestedBy: "Dr. Michael Chen",
    uploadedAt: "",
    status: "pending",
    fileUrl: "",
  },
  {
    reportId: "RPT-010",
    patientName: "Jennifer White",
    testType: "Fibromyalgia Panel",
    requestedBy: "Dr. James Reeves",
    uploadedAt: "2026-05-20T09:00:00Z",
    status: "uploaded",
    fileUrl: "/files/reports/rpt-010.pdf",
  },
];

// ─── MOCK PHARMACY INVENTORY ──────────────────────────────────────────────────

export const MOCK_PHARMACY_INVENTORY: PharmacyInventoryItem[] = [
  {
    medicineId: "MED-001",
    name: "Diclofenac Sodium 75mg",
    category: "NSAID / Analgesic",
    stock: 240,
    minStock: 50,
    expiryDate: "2027-08-01",
    supplier: "Cipla Ltd.",
    price: 0.85,
    status: "in_stock",
  },
  {
    medicineId: "MED-002",
    name: "Methocarbamol 750mg",
    category: "Muscle Relaxant",
    stock: 180,
    minStock: 40,
    expiryDate: "2027-03-15",
    supplier: "Sun Pharma",
    price: 1.2,
    status: "in_stock",
  },
  {
    medicineId: "MED-003",
    name: "Pantoprazole 40mg",
    category: "PPI / GI",
    stock: 320,
    minStock: 60,
    expiryDate: "2027-11-30",
    supplier: "Lupin Pharma",
    price: 0.65,
    status: "in_stock",
  },
  {
    medicineId: "MED-004",
    name: "Sumatriptan 50mg",
    category: "Triptan / Migraine",
    stock: 38,
    minStock: 30,
    expiryDate: "2027-06-01",
    supplier: "GSK Pharma",
    price: 4.5,
    status: "low_stock",
  },
  {
    medicineId: "MED-005",
    name: "Topiramate 25mg",
    category: "Anticonvulsant",
    stock: 150,
    minStock: 30,
    expiryDate: "2027-09-15",
    supplier: "Dr. Reddy's",
    price: 1.8,
    status: "in_stock",
  },
  {
    medicineId: "MED-006",
    name: "Metformin 1000mg",
    category: "Antidiabetic",
    stock: 450,
    minStock: 100,
    expiryDate: "2027-12-01",
    supplier: "Cipla Ltd.",
    price: 0.45,
    status: "in_stock",
  },
  {
    medicineId: "MED-007",
    name: "Empagliflozin 10mg",
    category: "SGLT2 Inhibitor",
    stock: 22,
    minStock: 25,
    expiryDate: "2027-04-30",
    supplier: "Boehringer Ingelheim",
    price: 6.2,
    status: "low_stock",
  },
  {
    medicineId: "MED-008",
    name: "Amlodipine 5mg",
    category: "Calcium Channel Blocker",
    stock: 0,
    minStock: 50,
    expiryDate: "2027-07-15",
    supplier: "Lupin Pharma",
    price: 0.3,
    status: "out_of_stock",
  },
  {
    medicineId: "MED-009",
    name: "Lisinopril 10mg",
    category: "ACE Inhibitor",
    stock: 210,
    minStock: 50,
    expiryDate: "2027-10-01",
    supplier: "Sun Pharma",
    price: 0.5,
    status: "in_stock",
  },
  {
    medicineId: "MED-010",
    name: "Ibuprofen 400mg",
    category: "NSAID / Analgesic",
    stock: 18,
    minStock: 80,
    expiryDate: "2026-09-30",
    supplier: "Cipla Ltd.",
    price: 0.4,
    status: "low_stock",
  },
  {
    medicineId: "MED-011",
    name: "Gabapentin 300mg",
    category: "Neuropathic Pain",
    stock: 165,
    minStock: 40,
    expiryDate: "2027-05-15",
    supplier: "Pfizer Ltd.",
    price: 1.1,
    status: "in_stock",
  },
  {
    medicineId: "MED-012",
    name: "Duloxetine 60mg",
    category: "SNRI / Antidepressant",
    stock: 90,
    minStock: 30,
    expiryDate: "2027-08-31",
    supplier: "Eli Lilly",
    price: 3.75,
    status: "in_stock",
  },
  {
    medicineId: "MED-013",
    name: "Tramadol 50mg",
    category: "Opioid Analgesic",
    stock: 0,
    minStock: 20,
    expiryDate: "2026-12-31",
    supplier: "Dr. Reddy's",
    price: 1.6,
    status: "out_of_stock",
  },
  {
    medicineId: "MED-014",
    name: "Methylcobalamin 500mcg",
    category: "Vitamin B12",
    stock: 380,
    minStock: 60,
    expiryDate: "2028-01-01",
    supplier: "Lupin Pharma",
    price: 0.55,
    status: "in_stock",
  },
  {
    medicineId: "MED-015",
    name: "Calcium + Vitamin D3",
    category: "Supplement",
    stock: 275,
    minStock: 50,
    expiryDate: "2027-11-15",
    supplier: "Abbott India",
    price: 0.9,
    status: "in_stock",
  },
];
