import type { User } from "@/types";
import type {
  AvailableSlot,
  PatientAppointment,
  PatientInvoice,
  PatientMedicine,
  PatientNotification,
  PatientPrescription,
  PatientProfile,
  PatientReport,
  TherapyProgressSession,
} from "@/types/patient";
import type {
  ActivityLog,
  CallLog,
  FollowUpReminder,
  GymPartnership,
  SalesDashboardStats,
  SalesLead,
  VisitRecord,
} from "@/types/sales";

// ──────────────────────────────────────────────
// SALES MOCK DATA
// ──────────────────────────────────────────────

export const SALES_STATS: SalesDashboardStats = {
  leadsThisWeek: 24,
  visitsCompleted: 18,
  conversionRate: 34,
  avgCallDuration: "4m 22s",
  leadsGrowth: 12,
  visitsGrowth: 8,
  conversionGrowth: 5,
};

export const SALES_LEADS: SalesLead[] = [
  {
    id: "sl1",
    name: "Greenfield General Hospital",
    phone: "+1-617-555-2001",
    email: "admin@greenfieldgh.com",
    source: "Cold Visit",
    stage: "qualified",
    assignedTo: "Marcus Reid",
    createdAt: "2026-05-01",
    followUpDate: "2026-05-22",
    value: 12000,
    notes: "Interested in physiotherapy referral partnership.",
  },
  {
    id: "sl2",
    name: "Northbridge Medical Center",
    phone: "+1-617-555-2002",
    email: "ceo@northbridgemc.com",
    source: "Referral",
    stage: "proposal",
    assignedTo: "Marcus Reid",
    createdAt: "2026-04-28",
    followUpDate: "2026-05-20",
    value: 18500,
    notes: "Proposal sent. Awaiting board approval.",
  },
  {
    id: "sl3",
    name: "Maplewood Community Clinic",
    phone: "+1-617-555-2003",
    email: "info@maplewoodclinic.org",
    source: "LinkedIn",
    stage: "contacted",
    assignedTo: "Marcus Reid",
    createdAt: "2026-05-05",
    followUpDate: "2026-05-21",
    value: 7500,
    notes: "Initial conversation done. Scheduling a site visit.",
  },
  {
    id: "sl4",
    name: "Eastview Rehabilitation Center",
    phone: "+1-617-555-2004",
    email: "director@eastviewrehab.com",
    source: "Trade Show",
    stage: "negotiation",
    assignedTo: "Marcus Reid",
    createdAt: "2026-04-15",
    followUpDate: "2026-05-19",
    value: 24000,
    notes: "Discussing contract terms. Decision expected next week.",
  },
  {
    id: "sl5",
    name: "Sunrise Orthopedic Group",
    phone: "+1-617-555-2005",
    email: "partnership@sunriseortho.com",
    source: "Cold Call",
    stage: "converted",
    assignedTo: "Marcus Reid",
    createdAt: "2026-04-02",
    value: 31000,
    notes: "Contract signed. Onboarding in progress.",
  },
  {
    id: "sl6",
    name: "Cityview Wellness Hospital",
    phone: "+1-617-555-2006",
    email: "admin@cityviewwellness.com",
    source: "Cold Visit",
    stage: "new",
    assignedTo: "Marcus Reid",
    createdAt: "2026-05-12",
    followUpDate: "2026-05-23",
    value: 9000,
    notes: "First contact made. Brochure delivered.",
  },
  {
    id: "sl7",
    name: "Harborview Medical Partners",
    phone: "+1-617-555-2007",
    email: "ops@harborviewmp.com",
    source: "Referral",
    stage: "lost",
    assignedTo: "Marcus Reid",
    createdAt: "2026-03-20",
    value: 15000,
    notes: "Chose competitor. Re-engage in Q3.",
  },
];

export const VISIT_HISTORY: VisitRecord[] = [
  {
    id: "v1",
    locationName: "Greenfield General Hospital",
    address: "450 Greenfield Blvd, Boston MA 02115",
    visitDate: "2026-05-15",
    checkInTime: "09:15 AM",
    checkOutTime: "10:45 AM",
    duration: "1h 30m",
    purpose: "Partnership Discussion",
    outcome: "Interested — scheduled follow-up",
    contactPerson: "Dr. Patricia Holt",
    leadsGenerated: 2,
    notes: "Tour of the rehab wing. Very positive reception.",
  },
  {
    id: "v2",
    locationName: "Northbridge Medical Center",
    address: "12 Northbridge Ave, Cambridge MA 02141",
    visitDate: "2026-05-13",
    checkInTime: "02:00 PM",
    checkOutTime: "03:20 PM",
    duration: "1h 20m",
    purpose: "Proposal Presentation",
    outcome: "Proposal accepted — moving to negotiation",
    contactPerson: "Mr. Dale Sutherland",
    leadsGenerated: 1,
    notes: "Presented service package. Requested pricing revision.",
  },
  {
    id: "v3",
    locationName: "Maplewood Community Clinic",
    address: "88 Maple Lane, Somerville MA 02144",
    visitDate: "2026-05-11",
    checkInTime: "11:00 AM",
    checkOutTime: "11:50 AM",
    duration: "50m",
    purpose: "Introduction Visit",
    outcome: "Interested — will review materials",
    contactPerson: "Dr. Sandra Voss",
    leadsGenerated: 1,
    notes: "Left brochure and demo access.",
  },
  {
    id: "v4",
    locationName: "Eastview Rehabilitation Center",
    address: "200 East Park Rd, Newton MA 02458",
    visitDate: "2026-05-08",
    checkInTime: "09:30 AM",
    checkOutTime: "11:15 AM",
    duration: "1h 45m",
    purpose: "Contract Negotiation",
    outcome: "Revised terms agreed upon",
    contactPerson: "Ms. Rachel Bloom",
    leadsGenerated: 3,
    notes: "Discussed SLA, pricing, and referral commission structure.",
  },
  {
    id: "v5",
    locationName: "Cityview Wellness Hospital",
    address: "5 City Plaza Dr, Brookline MA 02446",
    visitDate: "2026-05-06",
    checkInTime: "03:00 PM",
    checkOutTime: "03:45 PM",
    duration: "45m",
    purpose: "Cold Introduction",
    outcome: "Handed over brochure — callback requested",
    contactPerson: "Reception Manager",
    leadsGenerated: 1,
    notes: "Front desk visit. Meeting booked for next week.",
  },
];

export const HOSPITAL_CALL_LOGS: CallLog[] = [
  {
    id: "c1",
    contactName: "Dr. Patricia Holt",
    phone: "+1-617-555-2001",
    date: "2026-05-16",
    time: "10:00 AM",
    duration: "6m 15s",
    outcome: "callback_requested",
    notes: "She'll confirm partnership next Friday.",
    linkedLeadId: "sl1",
  },
  {
    id: "c2",
    contactName: "Mr. Dale Sutherland",
    phone: "+1-617-555-2002",
    date: "2026-05-14",
    time: "02:30 PM",
    duration: "8m 40s",
    outcome: "interested",
    notes: "Final pricing approved. Contract being drafted.",
    linkedLeadId: "sl2",
  },
  {
    id: "c3",
    contactName: "Dr. Sandra Voss",
    phone: "+1-617-555-2003",
    date: "2026-05-12",
    time: "04:15 PM",
    duration: "3m 22s",
    outcome: "interested",
    notes: "Wants a demo session for her team.",
    linkedLeadId: "sl3",
  },
  {
    id: "c4",
    contactName: "Harborview Admin",
    phone: "+1-617-555-2007",
    date: "2026-05-10",
    time: "11:00 AM",
    duration: "2m 05s",
    outcome: "not_interested",
    notes: "Signed with competitor PhysioPro.",
    linkedLeadId: "sl7",
  },
  {
    id: "c5",
    contactName: "Ms. Rachel Bloom",
    phone: "+1-617-555-2004",
    date: "2026-05-09",
    time: "03:00 PM",
    duration: "12m 18s",
    outcome: "converted",
    notes: "Agreement finalized. Sending onboarding doc.",
    linkedLeadId: "sl4",
  },
];

export const FOLLOW_UP_REMINDERS: FollowUpReminder[] = [
  {
    id: "f1",
    leadId: "sl1",
    leadName: "Greenfield General Hospital",
    phone: "+1-617-555-2001",
    dueDate: "2026-05-22",
    dueTime: "10:00 AM",
    type: "call",
    priority: "high",
    notes: "Confirm partnership decision with Dr. Holt.",
    isCompleted: false,
  },
  {
    id: "f2",
    leadId: "sl2",
    leadName: "Northbridge Medical Center",
    phone: "+1-617-555-2002",
    dueDate: "2026-05-20",
    dueTime: "02:00 PM",
    type: "email",
    priority: "high",
    notes: "Send revised contract with updated pricing.",
    isCompleted: false,
  },
  {
    id: "f3",
    leadId: "sl3",
    leadName: "Maplewood Community Clinic",
    phone: "+1-617-555-2003",
    dueDate: "2026-05-21",
    dueTime: "11:00 AM",
    type: "visit",
    priority: "medium",
    notes: "Demo session for clinical staff.",
    isCompleted: false,
  },
  {
    id: "f4",
    leadId: "sl6",
    leadName: "Cityview Wellness Hospital",
    phone: "+1-617-555-2006",
    dueDate: "2026-05-23",
    dueTime: "03:00 PM",
    type: "whatsapp",
    priority: "low",
    notes: "Send promo materials and service brochure.",
    isCompleted: false,
  },
  {
    id: "f5",
    leadId: "sl5",
    leadName: "Sunrise Orthopedic Group",
    phone: "+1-617-555-2005",
    dueDate: "2026-05-19",
    dueTime: "09:00 AM",
    type: "call",
    priority: "medium",
    notes: "Onboarding check-in call.",
    isCompleted: true,
  },
];

// ──────────────────────────────────────────────
// GYM/FITNESS MOCK DATA
// ──────────────────────────────────────────────

export const GYM_PARTNERSHIPS: GymPartnership[] = [
  {
    id: "g1",
    gymName: "Peak Performance Fitness",
    location: "120 Beacon St, Boston MA",
    contactPerson: "Kevin Shaw",
    phone: "+1-617-555-3001",
    partnershipType: "referral",
    status: "active",
    leadsGenerated: 18,
    conversions: 7,
    since: "2026-01-15",
    nextEvent: "2026-05-25 — Physio Camp",
  },
  {
    id: "g2",
    gymName: "IronBody CrossFit",
    location: "45 Huntington Ave, Boston MA",
    contactPerson: "Diana Moore",
    phone: "+1-617-555-3002",
    partnershipType: "session",
    status: "active",
    leadsGenerated: 12,
    conversions: 4,
    since: "2026-02-10",
    nextEvent: "2026-05-22 — Injury Prevention Workshop",
  },
  {
    id: "g3",
    gymName: "Boston Yoga & Wellness",
    location: "77 Newbury St, Boston MA",
    contactPerson: "Lisa Nguyen",
    phone: "+1-617-555-3003",
    partnershipType: "promo",
    status: "active",
    leadsGenerated: 9,
    conversions: 3,
    since: "2026-03-01",
    nextEvent: "2026-06-01 — Wellness Day",
  },
  {
    id: "g4",
    gymName: "ElevateX Training Center",
    location: "200 Commonwealth Ave, Boston MA",
    contactPerson: "Ryan Parks",
    phone: "+1-617-555-3004",
    partnershipType: "camp",
    status: "pending",
    leadsGenerated: 0,
    conversions: 0,
    since: "2026-05-10",
    nextEvent: "TBD — Awaiting approval",
  },
  {
    id: "g5",
    gymName: "FitZone Athletics",
    location: "33 Cambridge St, Cambridge MA",
    contactPerson: "Amanda Cole",
    phone: "+1-617-555-3005",
    partnershipType: "referral",
    status: "inactive",
    leadsGenerated: 5,
    conversions: 1,
    since: "2025-10-01",
  },
];

export const GYM_CALL_LOGS: CallLog[] = [
  {
    id: "gc1",
    contactName: "Kevin Shaw",
    phone: "+1-617-555-3001",
    date: "2026-05-16",
    time: "09:00 AM",
    duration: "5m 30s",
    outcome: "interested",
    notes: "Confirmed Physio Camp logistics for May 25.",
  },
  {
    id: "gc2",
    contactName: "Diana Moore",
    phone: "+1-617-555-3002",
    date: "2026-05-14",
    time: "11:30 AM",
    duration: "7m 12s",
    outcome: "interested",
    notes: "Workshop agenda agreed. Will promote to 80 members.",
  },
  {
    id: "gc3",
    contactName: "Ryan Parks",
    phone: "+1-617-555-3004",
    date: "2026-05-13",
    time: "03:15 PM",
    duration: "4m 45s",
    outcome: "callback_requested",
    notes: "Director not available. Will call back Thursday.",
  },
  {
    id: "gc4",
    contactName: "Amanda Cole",
    phone: "+1-617-555-3005",
    date: "2026-05-10",
    time: "10:00 AM",
    duration: "2m 10s",
    outcome: "not_interested",
    notes: "FitZone paused partnerships until new management.",
  },
];

export const GYM_LEADS: SalesLead[] = [
  {
    id: "gl1",
    name: "Alex Turner (Referred by Peak Performance)",
    phone: "+1-617-555-4001",
    email: "alex.turner@email.com",
    source: "Gym Referral",
    stage: "converted",
    assignedTo: "Sophie Lane",
    createdAt: "2026-05-02",
    value: 1800,
    notes: "Runner's knee. 6-session physio plan started.",
  },
  {
    id: "gl2",
    name: "Priya Kapoor (IronBody member)",
    phone: "+1-617-555-4002",
    email: "priya.k@email.com",
    source: "Gym Referral",
    stage: "qualified",
    assignedTo: "Sophie Lane",
    createdAt: "2026-05-08",
    followUpDate: "2026-05-21",
    value: 1400,
    notes: "Shoulder impingement. Assessment booked.",
  },
  {
    id: "gl3",
    name: "Chris Bennett (Boston Yoga)",
    phone: "+1-617-555-4003",
    email: "chris.b@email.com",
    source: "Gym Referral",
    stage: "contacted",
    assignedTo: "Sophie Lane",
    createdAt: "2026-05-10",
    followUpDate: "2026-05-22",
    value: 1200,
    notes: "Lower back pain. Waiting for appointment confirmation.",
  },
  {
    id: "gl4",
    name: "Maya Rodriguez (Peak Performance)",
    phone: "+1-617-555-4004",
    email: "maya.r@email.com",
    source: "Gym Referral",
    stage: "proposal",
    assignedTo: "Sophie Lane",
    createdAt: "2026-05-12",
    followUpDate: "2026-05-20",
    value: 2000,
    notes: "Post-marathon knee recovery program proposed.",
  },
  {
    id: "gl5",
    name: "Jordan White (IronBody)",
    phone: "+1-617-555-4005",
    email: "jordan.w@email.com",
    source: "Workshop",
    stage: "new",
    assignedTo: "Sophie Lane",
    createdAt: "2026-05-15",
    followUpDate: "2026-05-23",
    value: 900,
    notes: "Attended injury prevention workshop. Interested in assessment.",
  },
];

export const GYM_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "a1",
    date: "2026-05-16",
    time: "09:00 AM",
    type: "call",
    description: "Confirmed Physio Camp with Peak Performance Fitness",
    outcome: "Camp confirmed for May 25",
    linkedTo: "Peak Performance Fitness",
  },
  {
    id: "a2",
    date: "2026-05-15",
    time: "02:00 PM",
    type: "visit",
    description: "Visited IronBody CrossFit to discuss workshop logistics",
    outcome: "80 members registered for workshop",
    linkedTo: "IronBody CrossFit",
  },
  {
    id: "a3",
    date: "2026-05-13",
    time: "11:00 AM",
    type: "demo",
    description: "Live physio demo session at Boston Yoga & Wellness",
    outcome: "3 new leads generated",
    linkedTo: "Boston Yoga & Wellness",
  },
  {
    id: "a4",
    date: "2026-05-12",
    time: "04:30 PM",
    type: "email",
    description: "Sent partnership proposal to ElevateX Training Center",
    outcome: "Awaiting response",
    linkedTo: "ElevateX Training Center",
  },
  {
    id: "a5",
    date: "2026-05-10",
    time: "10:15 AM",
    type: "meeting",
    description: "Weekly sales review — Gym outreach performance Q2",
    outcome: "Targets revised upward 15%",
    linkedTo: "Internal",
  },
  {
    id: "a6",
    date: "2026-05-08",
    time: "01:00 PM",
    type: "whatsapp",
    description: "Sent physio promo flyer to Boston Yoga group",
    outcome: "2 enquiries received",
    linkedTo: "Boston Yoga & Wellness",
  },
];

export const PROMO_TRACKER_DATA = [
  { month: "Jan", referrals: 8, conversions: 3, sessions: 5 },
  { month: "Feb", referrals: 12, conversions: 5, sessions: 8 },
  { month: "Mar", referrals: 15, conversions: 6, sessions: 10 },
  { month: "Apr", referrals: 22, conversions: 9, sessions: 14 },
  { month: "May", referrals: 31, conversions: 14, sessions: 20 },
];

// ──────────────────────────────────────────────
// PATIENT PORTAL MOCK DATA
// ──────────────────────────────────────────────

export const MOCK_PATIENT_PROFILE: PatientProfile = {
  id: "pat001",
  patientId: "PSY-2024-011",
  name: "Jordan Mitchell",
  email: "jordan.mitchell@email.com",
  phone: "+1-617-555-8001",
  dob: "1990-04-12",
  gender: "Male",
  bloodGroup: "A+",
  address: "18 Riverside Drive, Boston MA 02134",
  medicalHistory:
    "Chronic lower back pain, ACL reconstruction (2022), mild hypertension",
  emergencyContactName: "Sarah Mitchell",
  emergencyContactPhone: "+1-617-555-8002",
  insurance: "BlueCross BlueShield PPO",
};

export const PATIENT_APPOINTMENTS: PatientAppointment[] = [
  {
    id: "pa1",
    doctorName: "Dr. James Reeves",
    doctorSpecialization: "Physical Medicine & Rehabilitation",
    department: "PMR",
    date: "2026-05-22",
    time: "10:00 AM",
    status: "upcoming",
    type: "Follow-up Consultation",
    location: "Room 204, PMR Wing",
    notes: "Bring latest X-ray and physiotherapy progress chart.",
  },
  {
    id: "pa2",
    doctorName: "Dr. Priya Sharma",
    doctorSpecialization: "Physiotherapy",
    department: "PMR",
    date: "2026-05-27",
    time: "02:30 PM",
    status: "upcoming",
    type: "Physiotherapy Session",
    location: "Physio Lab, Ground Floor",
  },
  {
    id: "pa3",
    doctorName: "Dr. James Reeves",
    doctorSpecialization: "Physical Medicine & Rehabilitation",
    department: "PMR",
    date: "2026-05-08",
    time: "09:30 AM",
    status: "completed",
    type: "Initial Consultation",
    location: "Room 204, PMR Wing",
    notes: "MRI suggested. Pain scale: 6/10.",
  },
  {
    id: "pa4",
    doctorName: "Dr. Aisha Khan",
    doctorSpecialization: "General Medicine",
    department: "General",
    date: "2026-04-20",
    time: "11:00 AM",
    status: "completed",
    type: "General Checkup",
    location: "Room 108, General Wing",
  },
  {
    id: "pa5",
    doctorName: "Dr. Priya Sharma",
    doctorSpecialization: "Physiotherapy",
    department: "PMR",
    date: "2026-04-10",
    time: "03:00 PM",
    status: "cancelled",
    type: "Physiotherapy Session",
    location: "Physio Lab, Ground Floor",
    notes: "Patient cancelled due to travel.",
  },
];

export const AVAILABLE_SLOTS: AvailableSlot[] = [
  {
    id: "s1",
    date: "2026-05-22",
    time: "09:00 AM",
    doctorName: "Dr. James Reeves",
    doctorSpecialization: "PMR",
    department: "PMR",
    isAvailable: true,
  },
  {
    id: "s2",
    date: "2026-05-22",
    time: "11:00 AM",
    doctorName: "Dr. Priya Sharma",
    doctorSpecialization: "Physiotherapy",
    department: "PMR",
    isAvailable: true,
  },
  {
    id: "s3",
    date: "2026-05-23",
    time: "10:00 AM",
    doctorName: "Dr. James Reeves",
    doctorSpecialization: "PMR",
    department: "PMR",
    isAvailable: true,
  },
  {
    id: "s4",
    date: "2026-05-23",
    time: "02:00 PM",
    doctorName: "Dr. Aisha Khan",
    doctorSpecialization: "General Medicine",
    department: "General",
    isAvailable: true,
  },
  {
    id: "s5",
    date: "2026-05-24",
    time: "09:30 AM",
    doctorName: "Dr. Michael Chen",
    doctorSpecialization: "Orthopedic Rehab",
    department: "PMR",
    isAvailable: true,
  },
  {
    id: "s6",
    date: "2026-05-24",
    time: "03:00 PM",
    doctorName: "Dr. Priya Sharma",
    doctorSpecialization: "Physiotherapy",
    department: "PMR",
    isAvailable: false,
  },
];

export const PATIENT_REPORTS: PatientReport[] = [
  {
    id: "r1",
    testName: "MRI Lumbar Spine",
    category: "Radiology",
    orderedBy: "Dr. James Reeves",
    date: "2026-05-10",
    status: "ready",
    fileSize: "4.2 MB",
    isCritical: false,
    summary:
      "L4-L5 disc herniation with mild nerve impingement. Physiotherapy recommended.",
  },
  {
    id: "r2",
    testName: "Complete Blood Count (CBC)",
    category: "Hematology",
    orderedBy: "Dr. Aisha Khan",
    date: "2026-04-21",
    status: "ready",
    fileSize: "0.8 MB",
    isCritical: false,
    summary: "All values within normal range. Mild vitamin D deficiency noted.",
  },
  {
    id: "r3",
    testName: "X-Ray Knee (Right)",
    category: "Radiology",
    orderedBy: "Dr. James Reeves",
    date: "2026-05-05",
    status: "ready",
    fileSize: "1.5 MB",
    isCritical: false,
    summary: "Mild joint space narrowing. ACL graft appears intact.",
  },
  {
    id: "r4",
    testName: "Blood Glucose Fasting",
    category: "Biochemistry",
    orderedBy: "Dr. Aisha Khan",
    date: "2026-05-15",
    status: "processing",
    isCritical: false,
  },
  {
    id: "r5",
    testName: "Electromyography (EMG)",
    category: "Neurology",
    orderedBy: "Dr. James Reeves",
    date: "2026-05-18",
    status: "pending",
    isCritical: false,
  },
];

export const PATIENT_PRESCRIPTIONS: PatientPrescription[] = [
  {
    id: "prx1",
    doctorName: "Dr. James Reeves",
    date: "2026-05-08",
    diagnosis: "Lumbar disc herniation with radiculopathy",
    status: "active",
    validUntil: "2026-06-08",
    medicines: [
      {
        name: "Diclofenac Sodium 75mg",
        dosage: "75mg",
        frequency: "Twice daily",
        duration: "4 weeks",
        instructions: "Take after food",
        refillsLeft: 2,
      },
      {
        name: "Pregabalin 75mg",
        dosage: "75mg",
        frequency: "Once at night",
        duration: "6 weeks",
        instructions: "Do not drive after taking",
        refillsLeft: 1,
      },
      {
        name: "Vitamin D3 60,000 IU",
        dosage: "60,000 IU",
        frequency: "Once weekly",
        duration: "8 weeks",
        instructions: "Take after fatty meal",
        refillsLeft: 3,
      },
    ],
  },
  {
    id: "prx2",
    doctorName: "Dr. Aisha Khan",
    date: "2026-04-20",
    diagnosis: "Mild hypertension, preventive management",
    status: "active",
    validUntil: "2026-07-20",
    medicines: [
      {
        name: "Amlodipine 5mg",
        dosage: "5mg",
        frequency: "Once daily",
        duration: "3 months",
        instructions: "Take in the morning",
        refillsLeft: 2,
      },
    ],
  },
  {
    id: "prx3",
    doctorName: "Dr. James Reeves",
    date: "2026-03-01",
    diagnosis: "Post-ACL rehabilitation",
    status: "completed",
    validUntil: "2026-04-01",
    medicines: [
      {
        name: "Ibuprofen 400mg",
        dosage: "400mg",
        frequency: "Three times daily",
        duration: "2 weeks",
        instructions: "Take with food. Stop if stomach upset.",
        refillsLeft: 0,
      },
    ],
  },
];

export const THERAPY_SESSIONS: TherapyProgressSession[] = [
  {
    id: "ts1",
    sessionNumber: 1,
    totalSessions: 12,
    date: "2026-04-15",
    therapistName: "Dr. Priya Sharma",
    sessionType: "Initial Assessment & Mobilization",
    progressPercent: 10,
    notes:
      "Baseline assessment completed. Severe stiffness in L4-L5 region. Started with gentle mobilization.",
    exercises: ["Knee-to-chest stretches", "Pelvic tilts", "Walking 10 min"],
    feedback:
      "Patient cooperative. Pain level 8/10 initially, reduced to 6/10 post-session.",
    painLevel: 8,
    mobility: 3,
    strength: 4,
  },
  {
    id: "ts2",
    sessionNumber: 3,
    totalSessions: 12,
    date: "2026-04-24",
    therapistName: "Dr. Priya Sharma",
    sessionType: "Core Strengthening Phase 1",
    progressPercent: 28,
    notes:
      "Pain reduced significantly. Introduced core stability exercises. Good compliance.",
    exercises: [
      "Bird-dog exercise",
      "Dead bug",
      "Cat-cow stretch",
      "Hip bridges",
    ],
    feedback: "Excellent improvement in 2 weeks. Mobility increasing.",
    painLevel: 5,
    mobility: 5,
    strength: 5,
  },
  {
    id: "ts3",
    sessionNumber: 6,
    totalSessions: 12,
    date: "2026-05-05",
    therapistName: "Dr. Priya Sharma",
    sessionType: "Functional Movement Training",
    progressPercent: 52,
    notes:
      "Patient performing daily activities with minimal pain. Introducing functional training.",
    exercises: [
      "Squat progression",
      "Romanian deadlift with light weight",
      "Lateral band walks",
      "Standing balance drills",
    ],
    feedback: "Halfway through program. Remarkable progress. Pain 3/10.",
    painLevel: 3,
    mobility: 7,
    strength: 6,
  },
  {
    id: "ts4",
    sessionNumber: 8,
    totalSessions: 12,
    date: "2026-05-12",
    therapistName: "Dr. Priya Sharma",
    sessionType: "Advanced Strengthening & Flexibility",
    progressPercent: 70,
    notes:
      "Returned to office work without discomfort. Progressing to advanced training.",
    exercises: [
      "Bulgarian split squat",
      "Single-leg deadlift",
      "Resistance band rows",
      "Yoga-based flexibility",
    ],
    feedback: "Near full mobility. Continuing strengthening phase.",
    painLevel: 2,
    mobility: 8,
    strength: 8,
  },
];

export const PATIENT_NOTIFICATIONS: PatientNotification[] = [
  {
    id: "pn1",
    type: "appointment",
    title: "Appointment Reminder",
    message:
      "Your appointment with Dr. James Reeves is scheduled for May 22 at 10:00 AM.",
    date: "2026-05-19",
    time: "09:00 AM",
    isRead: false,
    priority: "high",
  },
  {
    id: "pn2",
    type: "report",
    title: "MRI Report Ready",
    message:
      "Your MRI Lumbar Spine report is now available. Visit the Reports section to view.",
    date: "2026-05-10",
    time: "03:45 PM",
    isRead: false,
    priority: "high",
  },
  {
    id: "pn3",
    type: "medicine",
    title: "Medicine Refill Reminder",
    message:
      "Pregabalin 75mg has 1 refill remaining. Contact your doctor to renew the prescription.",
    date: "2026-05-18",
    time: "08:00 AM",
    isRead: false,
    priority: "medium",
  },
  {
    id: "pn4",
    type: "therapy",
    title: "Physiotherapy Session Scheduled",
    message:
      "Session #9 with Dr. Priya Sharma on May 27 at 2:30 PM. Wear comfortable clothing.",
    date: "2026-05-17",
    time: "10:00 AM",
    isRead: true,
    priority: "medium",
  },
  {
    id: "pn5",
    type: "billing",
    title: "Invoice Due",
    message:
      "Invoice INV-2026-008 for $420 is due on May 25. Pay online to avoid late fee.",
    date: "2026-05-15",
    time: "11:00 AM",
    isRead: true,
    priority: "medium",
  },
  {
    id: "pn6",
    type: "promotion",
    title: "Summer Wellness Package",
    message:
      "Enjoy 20% off on a 10-session physiotherapy package this June. Offer valid till June 30.",
    date: "2026-05-14",
    time: "02:00 PM",
    isRead: true,
    priority: "low",
  },
  {
    id: "pn7",
    type: "report",
    title: "X-Ray Report Uploaded",
    message:
      "Your X-Ray Knee (Right) report has been uploaded and is ready for review.",
    date: "2026-05-06",
    time: "04:15 PM",
    isRead: true,
    priority: "medium",
  },
];

export const PATIENT_INVOICES: PatientInvoice[] = [
  {
    id: "inv1",
    invoiceNumber: "INV-2026-008",
    date: "2026-05-15",
    dueDate: "2026-05-25",
    description: "Physiotherapy sessions + consultation",
    amount: 420,
    status: "pending",
    items: [
      { name: "Follow-up Consultation (Dr. Reeves)", quantity: 1, price: 120 },
      { name: "Physiotherapy Session × 2", quantity: 2, price: 150 },
    ],
  },
  {
    id: "inv2",
    invoiceNumber: "INV-2026-005",
    date: "2026-04-20",
    dueDate: "2026-04-30",
    description: "General consultation + CBC",
    amount: 185,
    status: "paid",
    items: [
      { name: "General Checkup (Dr. Khan)", quantity: 1, price: 100 },
      { name: "CBC Blood Test", quantity: 1, price: 85 },
    ],
  },
  {
    id: "inv3",
    invoiceNumber: "INV-2026-003",
    date: "2026-04-08",
    dueDate: "2026-04-18",
    description: "Initial PMR consultation + X-Ray",
    amount: 310,
    status: "paid",
    items: [
      { name: "Initial Consultation (Dr. Reeves)", quantity: 1, price: 150 },
      { name: "X-Ray Knee (Right)", quantity: 1, price: 160 },
    ],
  },
  {
    id: "inv4",
    invoiceNumber: "INV-2026-001",
    date: "2026-03-01",
    dueDate: "2026-03-11",
    description: "Physiotherapy assessment + session",
    amount: 240,
    status: "paid",
    items: [
      { name: "Physiotherapy Assessment", quantity: 1, price: 90 },
      { name: "Physiotherapy Session", quantity: 1, price: 150 },
    ],
  },
  {
    id: "inv5",
    invoiceNumber: "INV-2026-009",
    date: "2026-05-10",
    dueDate: "2026-05-17",
    description: "MRI Lumbar Spine",
    amount: 580,
    status: "overdue",
    items: [{ name: "MRI Lumbar Spine (Full)", quantity: 1, price: 580 }],
  },
];

// Additional MOCK_USERS entries for sales and patient
export const ADDITIONAL_MOCK_USERS: Record<string, User> = {
  sales: {
    id: "u4",
    name: "Marcus Reid",
    role: "sales" as unknown as import("@/types").UserRole,
    department: "Admin",
    email: "sales@clinic.com",
    phone: "+1-555-0104",
  },
  patient: {
    id: "u5",
    name: "Jordan Mitchell",
    role: "patient" as unknown as import("@/types").UserRole,
    department: "General",
    email: "patient@clinic.com",
    phone: "+1-617-555-8001",
  },
};
